sudo: required
dist: trusty

services:
  - postgresql

language: ruby

rvm:
  - 2.3.1

node_js:
  - "6"

before_install:
  - gem install bundler --no-rdoc --no-ri
  - npm install -g bower phantomjs-prebuilt

install:
  - cd Rails
  - bundle install
  - cd ../Ember/
  - npm install
  - bower install
  - ember --version
  - cd ..

script:
  - cd Rails
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - cd ../Ember/
  - ember test

after_script:
  - wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - heroku --version
  - git remote add heroku git@heroku.com:radetailing.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - ./build.sh

cache:
  bundler: true
  directories:
    - Ember/node_modules
    - Ember/bower_components

# safelist
# branches:
#   only:
#   - master
#   - appt_resource
