sudo: required
dist: trusty

services:
  - postgresql

language: ruby

rvm:
  - 2.3.1

node_js:
  - "6"

before_install:
  - gem install bundler --no-rdoc --no-ri
  - npm install -g bower phantomjs-prebuilt

install:
  - cd Rails
  - bundle install
  - cd ../Ember/
  - npm install
  - bower install
  - npm install -g ember-cli
  - ember --version
  - cd ..

script:
  - cd Rails
  - bundle exec rake db:drop db:create db:schema:load RAILS_ENV=test
  - bundle exec rspec
  - cd ../Ember/
  - ember test

cache:
  bundler: true
  directories:
    - Ember/node_modules
    - Ember/bower_components

# safelist
# branches:
#   only:
#   - master
#   - appt_resource
