development:
  adapter: postgresql
  encoding: utf8
  database: rad_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: rad_testing
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: rad_production
  pool: 5
